matrix:
  include:
    - os: linux
      env: OS=linux
      sudo: required
    - os: linux
      # Use QEMU 2.2 in ppa:wgrant/scalingstack-ppc64el.
      env: OS=linux-cross CROSS=1
      dist: trusty
      sudo: required
    - os: osx
      env: OS=osx
      # macOS 10.12 Sierra
      osx_image: xcode8.3
    - os: osx
      env: OS=osx
      # macOS 10.11 El Capitan
      osx_image: xcode7.3
    - os: osx
      env: OS=osx
      # macOS 10.10 Yosemite
      osx_image: xcode6.4
language: c
before_install:
  - if [[ "$OS" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$OS" == "linux" ]]; then sudo apt-get install gcc-multilib libc6-dbg:i386 valgrind; fi
  - if [[ "$OS" == "linux-cross" ]]; then sudo add-apt-repository ppa:wgrant/scalingstack-ppc64el -y; fi
  - if [[ "$OS" == "linux-cross" ]]; then sudo apt-get update -qq; fi
  - if [[ "$OS" == "linux-cross" ]]; then sudo apt-get install qemu-user gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu gcc-powerpc-linux-gnu gcc-powerpc64le-linux-gnu; fi
script:
  - cd test && make check CROSS=$CROSS
